project:
  type: website
  output-dir: _site
  preview:
    port: 4444

resources: 
  - CNAME

website:
  title: "ForeignAssistance dot gov emergency backup"

  repo-url: "https://github.com/andrewheiss/foreignassistance"
  repo-actions: [source, issue]

  navbar:
    pinned: true
    search: false

    background: "#0a314d"
    left:
      - live-example-dashboard.qmd
      - original-site.qmd
      - text: "Greenbook"
        href: greenbook.qmd
    right: 
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/foreignassistance

format:
  html:
    theme:
      - zephyr
      - custom.scss
